#! ../bin/bash

mv ./server/notedrop_nginx.conf /etc/nginx/sites-enabled/notedrop_nginx.conf
mv ./server/start_notedrop ../bin/start_notedrop
mv ./server/notedrop_supervisor.conf /etc/supervisor/conf.d/notedrop_supervisor.conf

service nginx restart
supervisorctl notedrop
supervisorctl update
